name: Pre Merge Checks
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    branches:
      - '*'

jobs:
  test:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Cancel Previous Runs
        if: github.event_name == 'pull_request'
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Gradle Folders
        uses: actions/cache@v3.0.1
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ matrix.kotlin-version }}-${{ hashFiles('build.gradle') }}
          restore-keys: |
            cache-gradle-${{ matrix.version }}-
            cache-gradle-

      - name: Run all the tests
        run: ./gradlew test

      - name: Stop Gradle
        run: ./gradlew --stop

  api-check:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Gradle Folders
        uses: actions/cache@v3.0.1
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('build.gradle') }}
          restore-keys: cache-gradle-

      - name: Run apiCheck
        run: ./gradlew apiCheck

      - name: Stop Gradle
        run: ./gradlew --stop

  build:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Gradle Folders
        uses: actions/cache@v3.0.1
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('build.gradle') }}
          restore-keys: cache-gradle-

      - name: Build
        run: ./gradlew build

      - name: Stop Gradle
        run: ./gradlew --stop
